/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "SymPwr.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(SymPwr); 

 SymPwr::SymPwr(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _A) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   A("A","A",this,_A)
 { 
 } 


 SymPwr::SymPwr(const SymPwr& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   A("A",this,other.A)
 { 
 } 



 Double_t SymPwr::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
    Double_t t = TMath::Abs(x);
        return TMath::Exp(-t/A);

 } 



