/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef SYMPWR
#define SYMPWR

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class SymPwr : public RooAbsPdf {
public:
  SymPwr() {} ; 
  SymPwr(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _A);
  SymPwr(const SymPwr& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new SymPwr(*this,newname); }
  inline virtual ~SymPwr() { }

protected:

  RooRealProxy x ;
  RooRealProxy A ;
  
  Double_t evaluate() const ;

private:

  ClassDef(SymPwr,1) // Your description goes here...
};
 
#endif
